version: '2'
services:
    ponto-app:
        image: ponto
        external_links:
            - ponto-postgresql:postgresql
            - ponto-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ponto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    ponto-postgresql:
        extends:
            file: postgresql.yml
            service: ponto-postgresql
    ponto-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ponto-elasticsearch
